live_config_reload = true

import = [
     "~/.config/alacritty/alacritty-theme/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
opacity = 0.9
title = "Alacritty"

[cursor.style]
shape = "Block"
blinking = "Always"

[font]
builtin_box_drawing = true
size = 10

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"


[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 1

[mouse]
hide_when_typing = true
